"""empty message

Revision ID: 58cff94d68be
Revises: ae920ab6621d
Create Date: 2021-10-19 17:39:07.182705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cff94d68be'
down_revision = 'ae920ab6621d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Car', 'price_avg',
                existing_type=sa.INTEGER(),
                nullable=False,
                existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Car', 'price_avg',
                existing_type=sa.INTEGER(),
                nullable=True,
                existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
