"""empty message

Revision ID: e38154464eed
Revises: 8f8c7dd43185
Create Date: 2021-10-19 17:24:51.822191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38154464eed'
down_revision = '8f8c7dd43185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Car', sa.Column('price_avg', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Car', 'price_avg')
    # ### end Alembic commands ###
